#!/usr/bin/env bash
# One-shot local setup, run with sudo from the repo checkout:
#   sudo ./deploy/setup-local.sh [ui-user] [node-binary]
# 1. checks preconditions (fips group, built frontend, Node 22.18+/23.6+/24+)
# 2. installs the privileged upgrade helper + its single sudoers rule for <ui-user>
# 3. installs deploy/fips-ui.service plus a drop-in that runs it from this checkout as <ui-user>
# 4. enables and (re)starts it, then checks /api/health
set -euo pipefail
[[ $(id -u) -eq 0 ]] || { echo "run with sudo" >&2; exit 1; }
here=$(cd "$(dirname "$0")/.." && pwd)
user=${1:-${SUDO_USER:-}}
[[ -n "$user" ]] && id "$user" >/dev/null 2>&1 || { echo "usage: $0 <ui-user> [node-binary]" >&2; exit 1; }
home=$(getent passwd "$user" | cut -d: -f6)
fail() { echo "error: $*" >&2; exit 1; }

# ---- preconditions (nothing is changed until these pass) ----
for p in "$here" "$home"; do [[ "$p" =~ [[:space:]%] ]] && fail "path '$p' contains whitespace or '%', which this script does not escape for systemd"; done
getent group fips >/dev/null || fail "group 'fips' does not exist; install and start the fips daemon first"
[[ -d "$here/web/dist" ]] || fail "$here/web/dist missing: run 'npm run build' first"
node=${2:-}
if [[ -z "$node" ]]; then
  # Resolve node the way the user's login shell would (covers mise/nvm/volta), then pin the real binary
  # so the unit does not depend on shims or PATH.
  node=$(sudo -u "$user" -H bash -lc 'command -v node' 2>/dev/null || true)
  [[ -n "$node" ]] || for c in /usr/bin/node /usr/local/bin/node; do [[ -x "$c" ]] && { node=$c; break; }; done
fi
[[ -n "$node" && -x "$node" ]] || fail "node not found; pass the binary as the second argument"
if [[ "$node" == */mise/shims/* ]]; then node=$(sudo -u "$user" -H bash -lc 'mise which node' 2>/dev/null || readlink -f "$node"); fi
node=$(readlink -f "$node")
ver=$("$node" -v 2>/dev/null | sed 's/^v//') || fail "$node -v failed"
IFS=. read -r maj min _ <<<"$ver"
# Node strips TypeScript without a flag from 22.18 and 23.6 (and every 24+); earlier 22.x/23.x need --experimental-strip-types.
(( maj >= 24 || (maj == 23 && min >= 6) || (maj == 22 && min >= 18) )) || fail "node $ver at $node is too old; 22.18+, 23.6+ or 24+ is required (unflagged TypeScript type stripping)"
[[ "$node" =~ [[:space:]%] ]] && fail "node path '$node' contains whitespace or '%'"
echo "== using node $ver at $node, UI user $user, checkout $here"

# ---- helper + sudoers rule (prints its own self-test) ----
echo "== helper"
"$here/deploy/install-upgrade-helper.sh" "$user"

# ---- unit + drop-in ----
echo "== unit"
id -nG "$user" | tr ' ' '\n' | grep -qx fips || { echo "adding $user to the fips group"; usermod -aG fips "$user"; }
install -m 0644 -o 0 -g 0 "$here/deploy/fips-ui.service" /etc/systemd/system/fips-ui.service
mkdir -p /etc/systemd/system/fips-ui.service.d
extra_groups=""; getent group systemd-journal >/dev/null && extra_groups="systemd-journal"
cat > /etc/systemd/system/fips-ui.service.d/local.conf <<UNIT
# Generated by deploy/setup-local.sh; the base unit is deploy/fips-ui.service.
[Service]
User=$user
SupplementaryGroups=$extra_groups
WorkingDirectory=$here
Environment=HOME=$home
# node's own directory first: npm (self-update) lives next to it when node comes from nvm, mise or a tarball.
Environment=PATH=$(dirname "$node"):/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=
ExecStart=$node server/index.ts
UNIT
if [[ ! -f /etc/default/fips-ui ]]; then
  install -m 0600 -o 0 -g 0 /dev/null /etc/default/fips-ui
  cat > /etc/default/fips-ui <<'ENV'
# Extra environment for fips-ui.service (see README). Keep this file mode 0600: it may hold tokens.
#FIPS_UI_TOKEN=change-me
#FIPS_UI_READ_ONLY=1
#FIPS_UI_ALLOW_SERVICE_CONTROL=1
#FIPS_UI_GITHUB_TOKEN=
ENV
fi
chmod 0600 /etc/default/fips-ui
systemctl daemon-reload
systemctl enable fips-ui.service >/dev/null
systemctl restart fips-ui.service

# ---- verify against the unit's effective host/port ----
echo "== verify"
host=127.0.0.1; port=8321
# shellcheck disable=SC1091
[[ -r /etc/default/fips-ui ]] && { set +u; . /etc/default/fips-ui; set -u; host=${FIPS_UI_HOST:-$host}; port=${FIPS_UI_PORT:-$port}; }
[[ "$host" == *:* ]] && host="[$host]"
ok=false
for _ in $(seq 1 30); do
  systemctl is-active --quiet fips-ui.service || { sleep 0.5; continue; }
  curl -fsS "http://$host:$port/api/health" 2>/dev/null && { ok=true; break; }
  sleep 0.5
done
echo
if ! $ok; then
  echo "fips-ui.service did not become healthy; recent log:" >&2
  journalctl -u fips-ui.service -n 20 --no-pager >&2 || true
  exit 1
fi
systemctl --no-pager --lines=0 status fips-ui.service | sed -n '1,4p'
echo; echo "done: http://$host:$port"
